#!/usr/bin/env python3
"""Scan project structure and generate changelog-categories.yml.

Analyzes the repository's directory structure to infer category mappings
for the daily-changes command. Preserves manually added categories from
an existing config file.

Usage:
    python3 refresh_categories.py [--repo-root <PATH>] [--dry-run]

Exit codes:
    0 — success
    1 — fatal error

Output (JSON to stdout):
    {
      "categories": {"APIs": ["src/api/"], "Frontend": ["src/components/"], ...},
      "preserved_from_existing": ["CustomCategory"],
      "config_path": "/abs/path/.claude/changelog-categories.yml",
      "written": true
    }
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


def find_repo_root(hint: str | None = None) -> Path:
    if hint:
        return Path(hint)
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True, check=True,
    )
    return Path(result.stdout.strip())


# Common directory patterns → category names
PATTERN_MAP = [
    # APIs / Backend
    (["src/api/", "api/", "src/routes/", "routes/", "endpoints/"], "APIs"),
    (["src/services/", "services/", "src/core/", "core/", "lib/", "src/lib/"], "Backend"),
    # Frontend
    (["src/components/", "components/", "src/pages/", "pages/", "src/views/", "views/", "src/ui/"], "Frontend"),
    (["src/styles/", "styles/", "css/", "static/css/"], "Styles"),
    # Data
    (["migrations/", "alembic/", "db/migrate/", "prisma/migrations/"], "Database"),
    (["models/", "src/models/", "src/db/", "src/data/"], "Data Models"),
    # Infrastructure
    (["deploy/", "infra/", "terraform/", "pulumi/", "k8s/", "kubernetes/", "helm/"], "Infrastructure"),
    ([".github/", ".gitlab-ci.yml", ".circleci/", "Jenkinsfile"], "CI/CD"),
    (["docker/", "Dockerfile"], "Docker"),
    # Documentation
    (["docs/", "doc/", "documentation/"], "Documentation"),
    # Testing
    (["tests/", "test/", "spec/", "__tests__/", "src/test/"], "Tests"),
    # Configuration
    (["config/", "configs/", ".config/", "settings/"], "Configuration"),
    # Scripts / Tools
    (["scripts/", "tools/", "bin/"], "Scripts"),
]


def scan_directories(repo_root: Path) -> dict[str, list[str]]:
    """Scan repo structure and return inferred category mappings."""
    categories: dict[str, list[str]] = {}

    for patterns, category_name in PATTERN_MAP:
        matched_paths = []
        for pattern in patterns:
            candidate = repo_root / pattern
            if candidate.exists():
                matched_paths.append(pattern)

        if matched_paths:
            categories[category_name] = matched_paths

    return categories


def load_existing_config(config_path: Path) -> dict[str, list[str]]:
    """Load existing YAML config (simple parser, no PyYAML dependency)."""
    if not config_path.exists():
        return {}

    categories: dict[str, list[str]] = {}
    current_category = None

    for line in config_path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not line.startswith(" ") and not line.startswith("\t") and stripped.endswith(":"):
            current_category = stripped[:-1]
            categories[current_category] = []
        elif current_category and stripped.startswith("- "):
            value = stripped[2:].strip().strip("'\"")
            categories[current_category].append(value)

    return categories


def write_yaml(config_path: Path, categories: dict[str, list[str]]):
    """Write categories as YAML (simple format, no PyYAML dependency)."""
    config_path.parent.mkdir(parents=True, exist_ok=True)

    lines = ["# Auto-generated by refresh_categories.py", "# Edit freely — manual changes are preserved on refresh", ""]
    for category, paths in sorted(categories.items()):
        lines.append(f"{category}:")
        for path in sorted(paths):
            lines.append(f"  - {path}")
    lines.append("")

    tmp_path = config_path.with_suffix(".yml.tmp")
    tmp_path.write_text("\n".join(lines))
    os.rename(tmp_path, config_path)


def main():
    parser = argparse.ArgumentParser(description="Refresh changelog categories config")
    parser.add_argument("--repo-root", help="Repository root path")
    parser.add_argument("--dry-run", action="store_true", help="Show inferred categories without writing")
    args = parser.parse_args()

    try:
        repo_root = find_repo_root(args.repo_root)
    except subprocess.CalledProcessError:
        print(json.dumps({"error": "Not a git repository"}))
        sys.exit(1)

    config_path = repo_root / ".claude" / "changelog-categories.yml"

    # Load existing config to preserve manual entries
    existing = load_existing_config(config_path)
    preserved = []

    # Scan and infer
    inferred = scan_directories(repo_root)

    # Merge: inferred categories win for paths, but keep any manually-added categories
    merged = dict(inferred)
    for cat, paths in existing.items():
        if cat not in merged:
            merged[cat] = paths
            preserved.append(cat)
        else:
            # Merge paths, keeping manual additions
            for p in paths:
                if p not in merged[cat]:
                    merged[cat].append(p)

    if not args.dry_run:
        write_yaml(config_path, merged)
        print(f"Wrote {config_path}", file=sys.stderr)

    print(json.dumps({
        "categories": merged,
        "preserved_from_existing": preserved,
        "config_path": str(config_path),
        "written": not args.dry_run,
    }))


if __name__ == "__main__":
    main()
